updated configuration
shopsys/PostgreSearchBundle pull request #1
Opened 2020-02-26 10:13 UTC by pesektomas

This PR fixed log message: ```The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "intaro_postgres_search" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.```

2020-02-27 12:22 UTC, grossmannmartin requested changes
Hi, really glad you thought about backward compatibility 👍 
can you please check some points I made?

2020-02-27 12:22 UTC, grossmannmartin commented on DependencyInjection/Configuration.php
> +            return $tree->root('jms_translation')->end();
Shouldn't it be like this?
```suggestion
            return $tree->root('intaro_postgres_search')->end();
```

2020-02-27 12:22 UTC, grossmannmartin commented on DependencyInjection/Configuration.php
> +            return $tree->root('jms_translation')->end();
Does 
```php
return $tree->root('intaro_postgres_search')->end();
``` 
behave the same as 
```php
$tree->root('intaro_postgres_search')->end();
return $tree;
```
?

2020-02-28 09:01 UTC, grossmannmartin approved these changes

2020-02-28 09:16 UTC, sslt approved these changes

2020-02-28 09:18 UTC, merged